DROP TABLE tag_item_files;
DROP TABLE tag_collection_items;
DROP TABLE tag_collections;
DROP TABLE tags;
DROP TABLE item_files;
DROP TABLE collection_items;
DROP TABLE collections;
DROP TABLE user_refresh_tokens;
DROP TABLE users;
